.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-REPL" "1" "July 2012" "" ""
.
.SH "NAME"
\fBgit\-repl\fR \- git read\-eval\-print\-loop
.
.SH "SYNOPSIS"
\fBgit\-repl\fR
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
GIT read\-eval\-print\-loop:
.
.IP "" 4
.
.nf

$ git repl

git> ls\-files
History\.md
Makefile
Readme\.md
bin/git\-changelog
bin/git\-count
bin/git\-delete\-branch
bin/git\-delete\-tag
bin/git\-ignore
bin/git\-release

git> quit
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
