.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-RELEASE" "1" "November 2014" "" ""
.
.SH "NAME"
\fBgit\-release\fR \- Commit, tag and push changes to the repository
.
.SH "SYNOPSIS"
\fBgit\-release\fR <tagname> [-c] [-r <remote>]
.
.SH "DESCRIPTION"
Commits changes with message "Release <tagname>", tags with the given <tagname> and pushes the branch / tags\. 
Optionally it generates a changelog (see git-changelog) and a remote can be defined\. The order of first -c or -r does not matter\.
.
.SH "OPTIONS"
<tagname>
.
.P
The name of the newly created tag\. Also used in tag comment\.
.
.P
-c
.
.P
Generates or populates the changelog with all commit message since the last tag. For more info see git-changelog.\.
.
.P
-r <remote>
.
.P
The "remote" repository that is destination of a push operation: it is passed to git push\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Release commit with the given <tagname>\.
.
.IP
$ git release 0\.1\.0
.
.IP "\(bu" 4
Release commit with the given <tagname> and populate changelog\.
.
.IP
$ git release 0\.1\.0 -c
.
.IP "\(bu" 4
Release commit with the given <tagname> and push to specific remote\.
.
.IP
$ git release 0\.1\.0 -r github
.
.IP "" 0
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
