.\" generated with Ronn-NG/v0.9.0
.\" http://github.com/apjanke/ronn-ng/tree/0.9.0
.TH "GIT\-CP" "1" "October 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-cp\fR \- Copy a file keeping its history
.SH "SYNOPSIS"
\fBgit\-cp\fR [\-\-commit\-template <template>] <current_filename> <destination_filename>
.SH "DESCRIPTION"
Copy a file keeping its git history\. This allows merge conflict handling\.
.P
Use \fB\-\-commit\-template\fR to customize each of the three commits created by the copy\. Every \fB{}\fR in the template is replaced with the default commit message, so text can be added before or after it\. The default template is \fB{}\fR, which leaves commit messages unchanged\.
.SH "EXAMPLES"
Copy README into README\.txt
.IP "" 4
.nf
$ git cp README README\.txt
.fi
.IP "" 0
.P
Associate the copy commits with issue #1252
.IP "" 4
.nf
$ git cp \-\-commit\-template \'#1252 {}\' README README\.txt
.fi
.IP "" 0
.P
Append a trailer to the copy commits
.IP "" 4
.nf
$ git cp \-\-commit\-template \'{} [skip ci]\' README README\.txt
.fi
.IP "" 0
.SH "AUTHOR"
Written by Rémy Hubscher <\fI\%mailto:hubscher\.remy@gmail\.com\fR>
.SH "REPORTING BUGS"
<\fI\%https://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fI\%https://github\.com/tj/git\-extras\fR>
.P
<\fI\%https://stackoverflow\.com/questions/16937359/git\-copy\-file\-preserving\-history/44036771#44036771\fR>
