.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-SUMMARY" "1" "June 2023" "" "Git Extras"
.SH "NAME"
\fBgit\-summary\fR \- Show repository summary
.SH "SYNOPSIS"
\fBgit\-summary\fR [\-\-dedup\-by\-email] [\-\-no\-merges] [<committish>]
.P
\fBgit\-summary\fR \-\-line [<path>]
.SH "DESCRIPTION"
Shows a summary of the repository or a path within it\.
.SH "OPTIONS"
<committish>
.P
Summarize only the range of commits included in the <committish>\.
.P
<path>
.P
Summarize only the range of files included in the <path>\.
.P
\-\-dedup\-by\-email
.P
Remove duplicate authors who belong to the same email address\. For example,
.IP "" 4
.nf
$ git summary
\|\.\|\.\|\.
133  TJ Holowaychuk            9\.9%
115  Tj Holowaychuk            8\.5%

$ git summary \-\-dedup\-by\-email
\|\.\|\.\|\.
248  TJ Holowaychuk            18\.4%
.fi
.IP "" 0
.P
\-\-no\-merges
.P
Exclude merge commits\.
.P
\-\-line
.P
Summarize with lines other than commits\. When \fB\-\-line\fR is specified, the last argument is treated as <path>\.
.P
This option can not be used together with \fB\-\-dedup\-by\-email\fR or \fB\-\-no\-merges\fR\.
.P
\-\-output\-style <style>
.P
Summarizes the repository and print the output according to the specified style\. Styles: * \fBtabular\fR: Prints the summary in a tabular form having a header in the first line and the values in the second\. Column separator is a \fB|\fR sorrounded by at least one space on each side\. * \fBoneline\fR: Prints the summary in a single line\. Fields are separated by a \fB/\fR sorrounded by one space on each side\.
.P
Some information like the authors cannot be displayed in this mode\.
.SH "EXAMPLES"
Outputs a repo summary:
.IP "" 4
.nf
$ git summary

project     : express
repo age    : 10 months ago
branch      : master
last active : 3 weeks ago
active on   : 93 days
commits     : 1893
files       : 111
uncommitted : 3
authors     :
 1285 visionmedia
  478 Tj Holowaychuk
   48 Aaron Heckmann
   34 csausdev
   26 ciaranj
    6 Guillermo Rauch
    3 Nick Poulden
    2 Brian McKinney
    2 Benny Wong
    1 Justin Lilly
    1 James Herdman
    1 Adam Sanderson
    1 Viktor Kelemen
    1 Gregory Ritter
    1 Greg Ritter
    1 ewoudj
    1 isaacs
    1 Matt Colyer
.fi
.IP "" 0
.P
This command can also take a committish, and will print a summary for the range of commits included in the committish:
.IP "" 4
.nf
$ git summary v42\.\.
.fi
.IP "" 0
.P
Outputs a repo summary by line:
.IP "" 4
.nf
$ git summary \-\-line

project  : git\-extras
lines    : 26820
authors  :
  \|\.\|\.\|\.
.fi
.IP "" 0
.P
Filter with the path:
.IP "" 4
.nf
$ git summary \-\-line bin/

project  : git\-extras
lines    : 4420
authors  :
  \|\.\|\.\|\.
.fi
.IP "" 0
.P
Tabular summary
.IP "" 4
.nf
$ git summary \-\-output\-style tabular
# Repo     | Age       | Last active | Active on | Commits | Uncommitted | Branch
git\-extras | 13 years  | 7 hours ago | 807 days  | 1703    | 3           | master
.fi
.IP "" 0
.P
Oneline summary
.IP "" 4
.nf
$ git summary \-\-output\-style oneline
git\-extras / age: 13 years / last active: 7 hours ago / active on 807 days / commits: 1703 / uncommitted: 3 / branch: master
.fi
.IP "" 0
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
