.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-RELEASE" "1" "October 2012" "" "Git Extras"
.
.SH "NAME"
\fBgit\-release\fR \- Commit, tag and push changes to the repository
.
.SH "SYNOPSIS"
\fBgit\-release\fR <tagname> [<remote>]
.
.SH "DESCRIPTION"
Commits changes with message "Release <tagname>", tags with the given <tagname> and pushes the branch / tags\.
.
.SH "OPTIONS"
<tagname>
.
.P
The name of the newly created tag\. Also used in tag comment\.
.
.P
<remote>
.
.P
The "remote" repository that is destination of a push operation: it is passed to git push\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Release commit with the given <tagname>\.
.
.IP
$ git release 0\.1\.0
.
.IP "\(bu" 4
Release commit with the given <tagname> and push to specific remote\.
.
.IP
$ git release 0\.1\.0 github
.
.IP "" 0
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/visionmedia/git\-extras\fR>
