.
.TH "GIT\-APPLE" "1" "September 2011" "" "Git Extras"
.
.SH "NAME"
\fBgit\-apple\fR \- Prints an apple
.
.SH "SYNOPSIS"
\fBgit\-apple\fR
.
.SH "DESCRIPTION"
Seriously, all it does is print a fucking apple.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Printing an apple:
.
.IP
$ git apple
.
.SH "AUTHOR"
Written by  Blake Taylor <\fIblakefrost@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
