.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-CONTRIB" "1" "October 2017" "" "Git Extras"
.
.SH "NAME"
\fBgit\-contrib\fR \- Show user\'s contributions
.
.SH "SYNOPSIS"
\fBgit\-contrib\fR [<username>|<email>]
.
.SH "DESCRIPTION"
Output a user\'s contributions to a project, based on the author name or email\. Returns multiple entries if there are more than one match\.
.
.SH "OPTIONS"
<username>
.
.P
The name or email of the user who owns the contributions\.
.
.SH "EXAMPLES"
.
.nf

Searching with a username

$ git contrib visionmedia
visionmedia (18):
  Export STATUS_CODES
  Moved help msg to node\-repl
  Added multiple arg support for sys\.puts(), print(), etc\.
  Fix stack output on socket error
  \.\.\.

Searching with a partial email

$ git contrib tj@
visionmedia (18):
  Export STATUS_CODES
  Moved help msg to node\-repl
  Added multiple arg support for sys\.puts(), print(), etc\.
  Fix stack output on socket error
  \.\.\.
.
.fi
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
