.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-REFACTOR" "1" "May 2018" "" "Git Extras"
.
.SH "NAME"
\fBgit\-refactor\fR \- Create refactor branch
.
.SH "SYNOPSIS"
\fBgit\-refactor\fR [\-r|\-\-remote [remote_name]] [finish] <name>
.
.SH "DESCRIPTION"
Create the given refactor branch
.
.SH "OPTIONS"
<\-r|\-\-remote [remote_name]>
.
.P
Setup a remote tracking branch using \fBremote_name\fR\. If \fBremote_name\fR is not supplied, use \fBorigin\fR by default\.
.
.P
<finish>
.
.P
Merge and delete the refactor branch\.
.
.P
<name>
.
.P
The name of the refactor branch\.
.
.SH "EXAMPLES"
.
.nf

$ git refactor mainlib_refactor
\.\.\.
$ git commit \-m "Some changes"
\.\.\.
$ git checkout master
$ git refactor finish mainlib_refactor

$ $ git refactor \-r upstream mainlib_refactor
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.br
Modified by Mark Pitman <\fImark\.pitman@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
