.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GIT\-BROWSE\-CI" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-browse\-ci\fR \- View the CI page for the current repository
.SH "SYNOPSIS"
\fBgit\-browse\-ci\fR [<remote_name>]
.SH "DESCRIPTION"
Opens the current git repository CI page in your default web browser\.
.SH "OPTIONS"
<remote_name>
.P
The name of the remote you wish to browse to\. Defaults to the current branch's configured remote, or \fBorigin\fR if not specified\.
.SH "EXAMPLES"
$ git browse\-ci
.P
$ git browse\-ci upstream
.SH "AUTHOR"
Written by Peter Benjamin <\fIhttps://github\.com/pbnj\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
