.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UNWIP" "1" "July 2017" "" ""
.
.SH "NAME"
\fBgit\-unwip\fR \- Undo a Work In Progress commit
.
.SH "SYNOPSIS"
\fBgit\-unwip\fR
.
.SH "DESCRIPTION"
Undo a Work In Progress commit\.
.
.SH "OPTIONS"
None
.
.SH "EXAMPLES"
Create a WIP commit which stores all changes in the working directory\.
.
.IP "" 4
.
.nf

$ git wip
.
.fi
.
.IP "" 0
.
.P
Later on, undo the commit and continue making changes\.
.
.IP "" 4
.
.nf

$ git unwip
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Andrew Sullivan Cant <\fImail@andrewsullivancant\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
