.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GIT\-DELETE\-MERGED\-BRANCHES" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-delete\-merged\-branches\fR \- Delete merged branches
.SH "SYNOPSIS"
\fBgit\-delete\-merged\-branches\fR
.SH "DESCRIPTION"
Deletes all branches merged in to current HEAD\. Does not delete the default branch, even if run from a branch that is a descendant of it\.
.SH "EXAMPLES"
.nf
$ git delete\-merged\-branches
.fi
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
