.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-FORK" "1" "June 2023" ""
.SH "NAME"
\fBgit\-fork\fR \- Fork a repo on github
.SH "SYNOPSIS"
\fBgit\-fork\fR [<github\-repo\-url>]
.SH "DESCRIPTION"
If a GitHub repo URL is given, the command forks the specified repository\. It performs the following actions:
.IP "1." 4
Forks the repo on GitHub\.
.IP "2." 4
Clones the repo into the current directory or the one specified with \fBd\fR or \fB\-\-target\-dir\fR\.
.IP "3." 4
Adds the original repo as a remote called \fBupstream\fR\.
.IP "" 0
.P
If a URL is not provided and the current directory is a GitHub repository, the command forks the current repo\. It performs the following actions:
.IP "1." 4
Forks the current repo
.IP "2." 4
Renames the \fBorigin\fR remote repo to \fBupstream\fR
.IP "3." 4
Adds the forked repo as a remote called \fBorigin\fR
.IP "" 0
.P
Remotes will use SSH if you have it configured with GitHub\. Otherwise, HTTPS will be used\.
.P
To create a fork of a project on GitHub via the command line, a personal access token is required\.
.P
The token is used for making the API call to create the fork on GitHub\.
.P
Refer to the GitHub API Documentation \fIhttps://docs\.github\.com/en/rest/reference/repos#forks\fR for more information\.
.P
Make sure that the personal access token has the necessary OAuth scopes for the repository\.
.P
You can configure the token by issuing the command:
.P
\fBgit config \-\-global \-\-add git\-extras\.github\-personal\-access\-token <your\-personal\-access\-token>\fR\.
.P
If you have multiple GitHub accounts and need to override the global token for a specific repository, use the command:
.P
\fBgit config git\-extras\.github\-personal\-access\-token <other\-acc\-personal\-access\-token>\fR\.
.SH "OPTIONS"
The following options are available:
.IP "\[ci]" 4
\fB\-h\fR, \fB\-\-help\fR: Print the help message and usage information\.
.IP "\[ci]" 4
\fB\-c\fR, \fB\-\-current\fR: Use the URL of the current Git repository as the source\.
.IP "\[ci]" 4
\fB\-t\fR, \fB\-\-token <token>\fR: Specify the GitHub personal access token\.
.IP "\[ci]" 4
\fB\-d\fR, \fB\-\-target\-dir <directory>\fR: Specify the target directory for cloning the forked repository\.
.IP "" 0
.SH "EXAMPLES"
Fork expect\.js:
.IP "" 4
.nf
$ git fork https://github\.com/LearnBoost/expect\.js
.fi
.IP "" 0
.P
or just:
.IP "" 4
.nf
$ git fork LearnBoost/expect\.js
.fi
.IP "" 0
.P
Then, the forked repository will be cloned into the \fBexpect\.js\fR directory locally\. You can navigate to the directory and check the remotes:
.IP "" 4
.nf
$ cd expect\.js && git remote \-v

  origin          git@github\.com:<user>/expect\.js (fetch)
  origin          git@github\.com:<user>/expect\.js (push)
  upstream        git@github\.com:LearnBoost/expect\.js (fetch)
  upstream        git@github\.com:LearnBoost/expect\.js (push)
.fi
.IP "" 0
.P
If the current dir is a clone of expect\.js, this has the same effect:
.IP "" 4
.nf
$ git fork
.fi
.IP "" 0
.SH "AUTHORS"
Written by Andrew Griffiths <\fImail@andrewgriffithsonline\.com\fR> Co\-authored by Marcelina Hołub <\fImholub@tutanota\.com\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
