.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-REPL" "1" "October 2017" "" "Git Extras"
.
.SH "NAME"
\fBgit\-repl\fR \- git read\-eval\-print\-loop
.
.SH "SYNOPSIS"
\fBgit\-repl\fR
.
.SH "DESCRIPTION"
Git read\-eval\-print\-loop\. Let\'s you run \fBgit\fR commands without typing \'git\'\.
.
.P
Commands can be prefixed with an exclamation mark (!) to be interpreted as a regular command\.
.
.P
Type \fBexit\fR or \fBquit\fR to end the repl session\.
.
.SH "COMMANDS"
<command>
.
.P
Interpreted as \fBgit <command>\fR\.
.
.P
!<command>
.
.P
Interpreted as \fB<command>\fR (not through \fBgit\fR)\.
.
.P
ls
.
.P
Equivalent of \'git ls\-files\'\.
.
.P
exit|quit
.
.P
Ends the repl session\.
.
.SH "EXAMPLES"
.
.nf

$ git repl
git version 2\.9\.2
git\-extras version 3\.0\.0
type \'ls\' to ls files below current directory,
\'!command\' to execute any command or just \'subcommand\' to execute any git subcommand

git (master)> ls\-files
History\.md
Makefile
Readme\.md
bin/git\-changelog
bin/git\-count
bin/git\-delete\-branch
bin/git\-delete\-tag
bin/git\-ignore
bin/git\-release

git (master)> !echo Straight from the shell!
Straight from the shell!

git (master)> quit
.
.fi
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
