.\" generated with Ronn-NG/v0.9.0
.\" http://github.com/apjanke/ronn-ng/tree/0.9.0
.TH "GIT\-CP" "1" "March 2020" "" "Git Extras"
.SH "NAME"
\fBgit\-cp\fR \- Copy a file keeping its history
.SH "SYNOPSIS"
\fBgit\-cp\fR <current_filename> <destination_filename>
.SH "DESCRIPTION"
Copy a file keeping its git history\. This allows merge conflict handling\.
.SH "EXAMPLES"
Copy README into README\.txt
.IP "" 4
.nf
$ git cp README README\.txt
.fi
.IP "" 0
.SH "AUTHOR"
Written by Rémy Hubscher <\fI\%mailto:hubscher\.remy@gmail\.com\fR>
.SH "REPORTING BUGS"
<\fI\%https://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fI\%https://github\.com/tj/git\-extras\fR>
.P
<\fI\%https://stackoverflow\.com/questions/16937359/git\-copy\-file\-preserving\-history/44036771#44036771\fR>
