.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GIT\-BROWSE" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-browse\fR \- View the web page for the current repository
.SH "SYNOPSIS"
\fBgit\-browse\fR [REMOTE\-NAME] [FILE\-NAME] [LINE\-1] [LINE\-2]
.SH "DESCRIPTION"
Opens the current git repository website in your default web browser\.
.SH "OPTIONS"
REMOTE\-NAME
.P
The name of the remote you wish to browse to\. Defaults to the first remote if not specified\.
.P
FILE\-NAME
.P
The name of the file you wish to browse to\.
.P
LINE\-1
.P
The line number of the file you wish to browse to\.
.P
LINE\-2
.P
The line range (from LINE\-1 to LINE\-2) of the file you wish to browse to\.
.SH "EXAMPLES"
$ git browse
.P
$ git browse upstream
.P
$ git browse upstream bin/git\-browse
.P
$ git browse upstream bin/git\-browse 42
.P
$ git browse upstream bin/git\-browse 1 42
.SH "AUTHOR"
Written by Mark Pitman <\fIhttps://github\.com/mapitman\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
