.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-BUG" "1" "October 2017" "" "Git Extras"
.
.SH "NAME"
\fBgit\-bug\fR \- Create bug branch
.
.SH "SYNOPSIS"
\fBgit\-bug\fR [\-r|\-\-remote [remote_name]] [finish] <name>
.
.SH "DESCRIPTION"
Create the given bug branch
.
.SH "OPTIONS"
<\-r|\-\-remote [remote_name]>
.
.P
Setup a remote tracking branch using \fBremote_name\fR\. If \fBremote_name\fR is not supplied, use \fBorigin\fR by default\.
.
.P
<finish>
.
.P
Merge and delete the bug branch\.
.
.P
<\-r
.
.P
<name>
.
.P
The name of the bug branch\.
.
.SH "EXAMPLES"
.
.nf

$ git bug bug\-123456
\.\.\.
$ git commit \-m "Some changes"
\.\.\.
$ git checkout master
$ git bug finish bug\-123456

$ git bug \-r 12345
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.br
Modified by Mark Pitman <\fImark\.pitman@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
