.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PSYKOREBASE" "1" "December 2015" "" ""
.
.SH "NAME"
\fBgit\-psykorebase\fR \- Rebase a branch with a merge commit
.
.SH "SYNOPSIS"
\fBgit\-psykorebase\fR <target_branch> [<feature_branch>] [\-\-no\-ff]
.
.P
\fBgit\-psykorebase\fR \-\-continue
.
.SH "DESCRIPTION"
Rebase the \fBfeature_branch\fR on top of the \fBtarget_branch\fR, the \fBfeature_branch\fR defaults to the current one\.
.
.SH "OPTIONS"
\fB\-\-no\-ff\fR Force a commit message even if there are no conflicts\.
.
.P
\fB\-\-continue\fR Continue the rebase after conflicts have been resolved\.
.
.SH "EXAMPLES"
Rebase current branch on top of master:
.
.IP "" 4
.
.nf

$ git psykorebase master \-\-no\-ff
.
.fi
.
.IP "" 0
.
.P
Handle conflicts:
.
.IP "" 4
.
.nf

$ git add README\.md
.
.fi
.
.IP "" 0
.
.P
Continue rebase:
.
.IP "" 4
.
.nf

$ git psykorebase \-\-continue
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Rémy Hubscher <\fIrhubscher@mozilla\.com\fR>
.
.P
Based on Benoît Bryon <\fIbenoit@marmelune\.net\fR> implementation in Python\.
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
.
.P
<\fIhttps://github\.com/benoitbryon/psykorebase\fR>
