.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-RENAME\-TAG" "1" "July 2012" "" ""
.
.SH "NAME"
\fBgit\-rename\-tag\fR \- Rename a tag
.
.SH "SYNOPSIS"
\fBgit\-rename\-tag\fR <old\-tag\-name> <new\-tag\-name>
.
.SH "DESCRIPTION"
Rename a tag (locally and remotely)
.
.SH "OPTIONS"
<old\-tag\-name>
.
.P
The name of the tag you want to rename\.
.
.P
<new\-tag\-name>
.
.P
The new name of the tag\.
.
.SH "EXAMPLES"
.
.nf

$ git tag test
$ git push \-\-tags
Total 0 (delta 0), reused 0 (delta 0)
To git@myserver\.com:myuser/myrepository\.git
 * [new tag]         test \-> test
$ git tag
test
$ git rename\-tag test test2
Deleted tag \'test\' (was 1111111)
Total 0 (delta 0), reused 0 (delta 0)
To git@myserver\.com:myuser/myrepository\.git
 * [new tag]         test2 \-> test2
remote: warning: Deleting a non\-existent ref\.
To git@myserver\.com:myuser/myrepository\.git
 \- [deleted]         refs/tag/test
$ git tag
test2
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
