.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-REBASE\-PATCH" "1" "September 2019" "" "Git Extras"
.SH "NAME"
\fBgit\-rebase\-patch\fR \- Rebases a patch
.SH "SYNOPSIS"
\fBgit\-rebase\-patch\fR <patch\-file>
.SH "DESCRIPTION"
Given you have a patch that doesn't apply to the current HEAD, but you know it applied to some commit in the past, \fBgit\-rebase\-patch\fR will help you find that commit and do a rebase\.
.SH "OPTIONS"
.TP
<patch\-file>
The patch to be applied\.
.SH "EXAMPLES"
Executing
.IP "" 4
.nf
$ git rebase\-patch test\.patch
.fi
.IP "" 0
.P
could give you something like that:
.IP "" 4
.nf
Trying to find a commit the patch applies to\|\.\|\.\|\.
Patch applied to dbcf408dd26 as 7dc8b23ae1a
First, rewinding head to replay your work on top of it\|\.\|\.\|\.
Applying: test\.patch
Using index info to reconstruct a base tree\|\.\|\.\|\.
Falling back to patching base and 3\-way merge\|\.\|\.\|\.
Auto\-merging README\.txt
.fi
.IP "" 0
.P
Then your last commit has the changes of the patch and is named \fItest\.patch\fR\.
.SH "AUTHOR"
Written by Niklas Fiekas <\fIniklas\.fiekas@tu\-clausthal\.de\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
