.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-COAUTHOR" "1" "August 2019" "" "Git Extras"
.
.SH "NAME"
\fBgit\-coauthor\fR \- Add a co\-author to the last commit
.
.SH "SYNOPSIS"
\fBgit\-coauthor\fR <co\-author> <co\-author\-email>
.
.SH "DESCRIPTION"
Add a co\-author to the last commit
.
.SH "OPTIONS"
<co\-author>
.
.P
The username of the co\-author you want to add\.
.
.P
<co\-author\-email>
.
.P
The email address of the author you want to add\.
.
.SH "EXAMPLES"
.
.nf

$ git coauthor user user@email\.com
.
.fi
.
.SH "AUTHOR"
Written by Jacob Herrington \fIjacobherringtondeveloper@gmail\.com\fR
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
