.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-DELETE\-GONE\-BRANCHES" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-delete\-gone\-branches\fR \- Delete branches where the remote branch is gone
.SH "SYNOPSIS"
\fBgit\-delete\-gone\-branches\fR
.SH "DESCRIPTION"
Delete all branches where the remote branch is gone because it was deleted\. This is common when you work with GitHub, you have your personal repository, and use the "Delete" button to delete the branch after it is merged with the main branch\.
.SH "EXAMPLES"
.nf
$ git delete\-gone\-branches
.fi
.SH "AUTHOR"
Written by Mats Kindahl <mats@kindahl\.net>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
