.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GIT\-SHOW\-MERGED\-BRANCHES" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-show\-merged\-branches\fR \- Show merged branches
.SH "SYNOPSIS"
\fBgit\-show\-merged\-branches\fR
.SH "DESCRIPTION"
Show branches merged in to current HEAD, excluding the default branch\.
.SH "EXAMPLES"
.nf
$ git show\-merged\-branches
.fi
.SH "AUTHOR"
Written by Paul Schreiber <\fIpaulschreiber@gmail\.com\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
