.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-BUG" "1" "July 2012" "" ""
.
.SH "NAME"
\fBgit\-bug\fR \- Create bug branch
.
.SH "SYNOPSIS"
\fBgit\-bug\fR [finish] <name>
.
.SH "DESCRIPTION"
Create the given bug branch
.
.SH "OPTIONS"
<finish>
.
.P
Merge and delete the bug branch\.
.
.P
<name>
.
.P
The name of the bug branch\.
.
.SH "EXAMPLES"
.
.nf

$ git bug bug\-123456
\.\.\.
$ git commit \-m "Some changes"
\.\.\.
$ git checkout master
$ git bug finish bug\-123456
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
