.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-LOCAL\-COMMITS" "1" "January 2022" "" "Git Extras"
.SH "NAME"
\fBgit\-local\-commits\fR \- List local commits
.SH "SYNOPSIS"
\fBgit\-local\-commits\fR <args>
.SH "DESCRIPTION"
Lists commits in the local branch that have not been pushed to the remote tracked branch\. This requires that HEAD points to a branch which is tracking another branch\.
.SH "OPTIONS"
<args>
.P
All arguments passed to \fBgit\-local\-commits\fR will be passed directly to \fBgit\-log\fR\.
.SH "EXAMPLES"
.nf
$ git local\-commits \-\-graph
.fi
.SH "AUTHOR"
Written by Michael Komitee <\fImkomitee@gmail\.com\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
