.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GIT\-SETUP" "1" "March 2026" "" "Git Extras"
.SH "NAME"
\fBgit\-setup\fR \- Set up a git repository
.SH "SYNOPSIS"
\fBgit\-setup\fR [\-m <message>] [<directory>]
.SH "DESCRIPTION"
Set up a git repository if one doesn't exist, add all files and make an initial commit\.
.SH "OPTIONS"
\-m <message>
.P
Use <message> as the initial commit message\.
.P
<directory>
.P
The name of a new directory to setup\. By default, the current working directory\.
.SH "EXAMPLES"
.nf
$ git setup path/to/repository
.fi
.SH "AUTHOR"
Written by Aggelos Orfanakos <\fIagorf@agorf\.gr\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
