.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-DELETE\-MERGED\-BRANCHES" "1" "November 2012" "" "Git Extras"
.
.SH "NAME"
\fBgit\-delete\-merged\-branches\fR \- Delete merged branches
.
.SH "SYNOPSIS"
\fBgit\-delete\-merged\-branches\fR [\-f|\-\-force]
.
.SH "DESCRIPTION"
Deletes all branches merged into current HEAD\. Does not delete \fImaster\fR, even if ran from a branch that is \fImaster\fR descendant\. Asks before deleting anything, unless it is run with \fI\-\-force\fR option\.
.
.SH "OPTIONS"
\-f, \-\-force
.
.P
Delete merged branches without asking user for confirmation\.
.
.SH "EXAMPLES"
.
.nf

$ git delete\-merged\-branches
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/visionmedia/git\-extras\fR>
