.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "GIT\-RENAME\-FILE" "1" "July 2024" "" "Git Extras"
.SH "NAME"
\fBgit\-rename\-file\fR \- Rename a file or directory and ensure Git recognizes the change, regardless of filesystem case-sensitivity.
.SH "SYNOPSIS"
\fBgit\-rename\-file\fR [OPTIONS] <source> <destination>
.SH "DESCRIPTION"
The \fBgit\-rename\-file\fR command renames a file or directory and ensures Git recognizes the change, regardless of filesystem case-sensitivity. It combines the functionality of the \fBmv\fR command and \fBgit mv\fR.
This is particularly useful for renaming files or directories to change only their case, which might not be detected by Git on case-insensitive filesystems.
.SH "OPTIONS"
\fB\-h\fR, \fB\-\-help\fR
.RS
Show usage information.
.RE
.SH "EXAMPLES"
Rename a file:
.RS
\fBgit\-rename\-file old_filename new_filename\fR
.RE
Rename a directory:
.RS
\fBgit\-rename\-file old_directory new_directory\fR
.RE
.SH "AUTHOR"
Written by Zachary Miller <\fI\%codebyzach@gmail.com\fR>
.SH "REPORTING BUGS"
<\fI\%https://github.com/tj/git-extras/issues\fR>
.SH "SEE ALSO"
<\fI\%https://github.com/tj/git-extras\fR>
