.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-REPL" "1" "September 2024" "" "Git Extras"
.SH "NAME"
\fBgit\-repl\fR \- git read\-eval\-print\-loop
.SH "SYNOPSIS"
\fBgit\-repl\fR
.P
\fBgit\-repl\fR [command\|\.\|\.\|\.]
.SH "DESCRIPTION"
Git read\-eval\-print\-loop\. Lets you run \fBgit\fR commands without typing 'git'\.
.P
Commands can be prefixed with an exclamation mark (!) to be interpreted as a regular shell command\.
.P
Any arguments to git repl will be taken collectively as the first command to execute in the repl\.
.P
Type \fBexit\fR, \fBquit\fR, or \fBq\fR to end the repl session\. Ctrl\-D and Ctrl\-C will also work\.
.SH "COMMANDS"
<command>
.P
Interpreted as \fBgit <command>\fR\.
.P
!<command>
.P
Interpreted as \fB<command>\fR (not through \fBgit\fR)\.
.P
ls
.P
Equivalent of 'git ls\-files'\.
.P
exit|quit|q
.P
Ends the repl session\.
.SH "EXAMPLES"
.nf
$ git repl
git version 2\.34\.1
git\-extras version 7\.3\.0
Type 'ls' to ls files below current directory; '!command' to execute any command or just 'subcommand' to execute any git subcommand; 'quit', 'exit', 'q', ^D, or ^C to exit the git repl\.

git (master)> ls\-files
History\.md
Makefile
Readme\.md
bin/git\-changelog
bin/git\-count
bin/git\-delete\-branch
bin/git\-delete\-tag
bin/git\-ignore
bin/git\-release

git (master)> !echo Straight from the shell!
Straight from the shell!

git (master)> quit
.fi
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>\. Updated by Wyatt S Carpenter to add display of the previous command's exit status, 'q', and the ability to pass in the initial command as arguments\.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
