.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-RELEASE" "1" "April 2022" "" "Git Extras"
.
.SH "NAME"
\fBgit\-release\fR \- Commit, tag and push changes to the repository
.
.SH "SYNOPSIS"
\fBgit\-release\fR [<tagname> | \-\-semver <name>] [\-r <remote>] [\-m <commit info>] [\-\-no\-empty\-commit] [\-c] [\-s] [\-u <key\-id>] [\-\-prefix <tag prefix>] [[\-\-] <hook arguments\.\.\.>]
.
.SH "DESCRIPTION"
Commits changes with message "Release <tagname>" or custom commit information, tags with the given <tagname> and pushes the branch / tags\.
.
.P
This command always creates a release commit, which could be empty if nothing changed\. It works like \fBgit merge \-\-no\-ff\fR\. If you don\'t like the behavior, you could add \fB\-\-no\-empty\-commit\fR to skip it\.
.
.P
Optionally it generates a changelog (see git\-changelog) and a remote can be defined\. The order of first \-c or \-r does not matter\.
.
.P
If \fB\.git/hook/pre\-release\fR or \fB\.git/hook/post\-release\fR exist, they will be triggered with \fBtagname\fR and extra hook arguments before/after the release\.
.
.SH "OPTIONS"
\-\-semver <name>
.
.P
If the latest tag in your repo matches the semver format requirement, you could increase part of it as the new release tag with this option\. The name must be one of the \fBmajor\fR, \fBminor\fR, \fBpatch\fR\. For example, assumed the latest tag is \fB4\.4\.0\fR, with \fBgit release \-\-semver minor\fR you will make a new release with tag \fB4\.5\.0\fR\. Use \fB\-\-prefix\fR if tag has a character before semver\.
.
.P
<tagname>
.
.P
The name of the newly created tag\. Also used in tag comment\.
.
.P
\-\-prefix <tag prefix>
.
.P
Use a prefix with a semver tag\. \fBgit release \-\-semver minor \-\-prefix r\fR would increment the latest tag r4\.4\.0 to r4\.5\.0\. This prefix can be any length, without spaces\.
.
.P
\-r <remote>
.
.P
The "remote" repository that is destination of a push operation: it is passed to git push\.
.
.P
\-m <commit info>
.
.P
use the custom commit information instead of the default message "Release <tagname>" \.
.
.P
\-\-no\-empty\-commit
.
.P
Avoid creating empty commit if nothing could be committed\.
.
.P
\-c
.
.P
Generates or populates the changelog with all commit message since the last tag\. For more info see git\-changelog\.\.
.
.P
\-s
.
.P
Create a signed and annotated tag\.
.
.P
\-u <key\-id>
.
.P
Create a tag, annotated and signed with the given key\.
.
.P
[\-\-] hook arguments\.\.\.
.
.P
The arguments listed after "\-\-" separator will be passed to pre/post\-release hook following the \fBtagname\fR\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Release commit with the given <tagname>\.
.
.IP
$ git release 0\.1\.0
.
.IP "\(bu" 4
Release commit with the given <tagname> and custom commit message\.
.
.IP
$ git release 0\.1\.0 \-m "+ powerful feature added\."
.
.IP "\(bu" 4
Release commit with the given <tagname> and push to specific remote\.
.
.IP
$ git release 0\.1\.0 \-r github
.
.IP "\(bu" 4
Release commit with the given <tagname> and populate changelog\.
.
.IP
$ git release 0\.1\.0 \-c
.
.IP "\(bu" 4
Release commit with the given <tagname>, populate changelog, and push to specific remote\.
.
.IP
$ git release 0\.1\.0 \-r github \-c
.
.IP "\(bu" 4
Release commit with the given <tagname>, pass <tagname> and extra argument to release hook, populate changelog, and push to specific remote\.
.
.IP
$ git release 0\.1\.0 \-r github \-c \-\- \-\-signature\-required
.
.IP "" 0
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR> Extended by David Hartmann <\fIdh@tsl\.io\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
