.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-DELETE\-BRANCH" "1" "October 2010" "" "Git Extras"
.
.SH "NAME"
\fBgit\-delete\-branch\fR \- Delete branches
.
.SH "SYNOPSIS"
\fBgit\-delete\-branch\fR <branchname>
.
.SH "DESCRIPTION"
Deletes local and remote branch named <branchname>\.
.
.SH "OPTIONS"
<branchname>
.
.P
The name of the branch to delete\.
.
.SH "EXAMPLES"
.
.nf

$ git delete\-branch integration
.
.fi
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
