.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "GIT\-WIP" "1" "May 2025" "" "Git Extras"
.SH "NAME"
\fBgit\-wip\fR \- Create a Work In Progress commit
.SH "SYNOPSIS"
\fBgit\-wip\fR
.SH "DESCRIPTION"
Create a Work In Progress commit, include all files in the working directory\.
.SH "OPTIONS"
None
.SH "EXAMPLES"
Create a WIP commit which stores all changes in the working directory\.
.IP "" 4
.nf
$ git wip
.fi
.IP "" 0
.P
Later on, undo the commit and continue making changes\.
.IP "" 4
.nf
$ git unwip
.fi
.IP "" 0
.SH "AUTHOR"
Written by Andrew Sullivan Cant <\fImail@andrewsullivancant\.ca\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
