.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-DELETE\-SUBMODULE" "1" "July 2012" "" ""
.
.SH "NAME"
\fBgit\-delete\-submodule\fR \- Delete submodules
.
.SH "SYNOPSIS"
\fBgit\-delete\-submodule\fR <path>
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
<path>
.
.P
The path of the submodule to delete\.
.
.SH "EXAMPLES"
.
.nf

$ git delete\-submodule lib/foo
.
.fi
.
.SH "AUTHOR"
Written by Jonhnny Weslley <\fIjw@jonhnnyweslley\.net\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
