.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GIT\-UNLOCK" "1" "December 2021" "" "Git Extras"
.SH "NAME"
\fBgit\-unlock\fR \- Unlock a file excluded from version control
.SH "SYNOPSIS"
\fBgit\-unlock\fR <filename>
.SH "DESCRIPTION"
Unlock local files from version control\.
.SH "OPTIONS"
<filename>
.P
The name of the filename\.
.SH "EXAMPLES"
.nf
$ git unlock config/database\.yml
.fi
.SH "AUTHOR"
Written by Julio Napuri <\fIjulionc@gmail\.com\fR>
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
