.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LOCKED" "1" "October 2017" "" "Git Extras"
.
.SH "NAME"
\fBgit\-locked\fR \- ls files that have been locked
.
.SH "SYNOPSIS"
\fBgit\-locked\fR
.
.SH "DESCRIPTION"
List local files that have been locked
.
.SH "EXAMPLES"
.
.nf

$ git lock config/database\.yml
$ git locked
config/database\.yml
.
.fi
.
.SH "AUTHOR"
Written by Kevin Woo <\fIkevinawoo@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
