.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-ROOT" "1" "November 2012" "" ""
.
.SH "NAME"
\fBgit\-root\fR \- Show repository root directory
.
.SH "SYNOPSIS"
\fBgit\-root\fR
.
.SH "DESCRIPTION"
Shows the root directory of the repository\.
.
.SH "EXAMPLES"
Outputs a repo root directory:
.
.IP "" 4
.
.nf

$ git root

    /home/username/repos/myrepo
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Richard Midwinter <\fIrich\.midwinter@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/visionmedia/git\-extras\fR>
