.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UNDO" "1" "June 2018" "" "Git Extras"
.
.SH "NAME"
\fBgit\-undo\fR \- Remove latest commits
.
.SH "SYNOPSIS"
\fBgit\-undo\fR [\-s, \-\-soft, \-h, \-\-hard] [<commitcount>]
.
.SH "DESCRIPTION"
Removes the latest commits\.
.
.SH "OPTIONS"
\-\-soft or \-s
.
.P
Rolls back the commit(s) but leaves the changes in the staging area\.
.
.P
\-\-hard or \-h
.
.P
This option wipes your commit(s), so that your changes cannot be recovered\. Use with care\. To avoid being confused with \fB\-\-help\fR, there will be a confirmation when \fB\-h\fR is specified\.
.
.P
<commitcount>
.
.P
Number of commits to remove\. Defaults to \fI1\fR, thus remove the latest commit\.
.
.SH "EXAMPLES"
Removes the latest commit\.
.
.IP "" 4
.
.nf

$ git undo
.
.fi
.
.IP "" 0
.
.P
Removes the latest commit, restoring the staging area\.
.
.IP "" 4
.
.nf

$ git undo \-s
.
.fi
.
.IP "" 0
.
.P
Remove the latest 3 commits:
.
.IP "" 4
.
.nf

$ git undo 3
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Kenneth Reitz <\fIme@kennethreitz\.com\fR> and Nick Lombard <\fIgithub@jigsoft\.co\.za\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
