.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-FRESH\-BRANCH" "1" "October 2010" "" "Git Extras"
.
.SH "NAME"
\fBgit\-fresh\-branch\fR \- Create fresh branches
.
.SH "SYNOPSIS"
\fBgit\-fresh\-branch\fR <branchname>
.
.SH "DESCRIPTION"
Creates empty local branch named <branchname>\.
.
.SH "OPTIONS"
<branchname>
.
.P
The name of the branch to create\.
.
.SH "EXAMPLES"
.
.nf

$ git fresh\-branch docs
.
.fi
.
.SH "AUTHOR"
Written by Kenneth Reitz <\fIme@kennethreitz\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
