.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-CREATE\-BRANCH" "1" "July 2012" "" ""
.
.SH "NAME"
\fBgit\-create\-branch\fR \- Create branches
.
.SH "SYNOPSIS"
\fBgit\-create\-branch\fR <branchname>
.
.SH "DESCRIPTION"
Creates local and remote branch named <branchname>\.
.
.SH "OPTIONS"
<branchname>
.
.P
The name of the branch to create\.
.
.SH "EXAMPLES"
.
.nf

$ git create\-branch integration
.
.fi
.
.SH "AUTHOR"
Written by Jonhnny Weslley <\fIjw@jonhnnyweslley\.net\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
