.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-INFO" "1" "July 2012" "" ""
.
.SH "NAME"
\fBgit\-info\fR \- Returns information on current repository
.
.SH "SYNOPSIS"
\fBgit\-info\fR
.
.SH "DESCRIPTION"
Shows the following information about a repository:
.
.IP "1." 4
Remote Url(s)
.
.IP "2." 4
Remote Branches
.
.IP "3." 4
Local Branches
.
.IP "4." 4
Most recent commit
.
.IP "5." 4
Configuration Info
.
.IP "" 0
.
.SH "OPTIONS"
N/A
.
.SH "EXAMPLES"
Outputs info about a repo:
.
.IP "" 4
.
.nf

$ git info

## Remote URLs:

origin      git@github\.com:sampleAuthor/git\-extras\.git (fetch)
origin      git@github\.com:sampleAuthor/git\-extras\.git (push)

## Remote Branches:

origin/HEAD \-> origin/master
origin/myBranch

## Local Branches:

myBranch
* master

## Most Recent Commit:

commit e3952df2c172c6f3eb533d8d0b1a6c77250769a7
Author: Sample Author <sampleAuthor@gmail\.com>

Added git\-info command\.

Type \'git log\' for more commits, or \'git show <commit id>\' for full commit details\.

## Configuration (\.git/config):

color\.diff=auto
color\.status=auto
color\.branch=auto
user\.name=Sample Author
user\.email=sampleAuthor@gmail\.com
core\.repositoryformatversion=0
core\.filemode=true
core\.bare=false
core\.logallrefupdates=true
core\.ignorecase=true
remote\.origin\.fetch=+refs/heads/*:refs/remotes/origin/*
remote\.origin\.url=git@github\.com:mub/git\-extras\.git
branch\.master\.remote=origin
branch\.master\.merge=refs/heads/master
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Leila Muhtasib <\fImuhtasib@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
