.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-BACK" "1" "February 2020" "" "Git Extras"
.
.SH "NAME"
\fBgit\-back\fR \- Undo and Stage latest commits
.
.SH "SYNOPSIS"
\fBgit\-back\fR [<commitcount>]
.
.SH "DESCRIPTION"
Deprecated\. Use \'git undo \-\-soft [commitcount]\' instead\.
.
.P
Removes the latest commits, and add their changes to your staging area\.
.
.SH "OPTIONS"
<commitcount>
.
.P
Number of commits to remove\. Defaults to \fI1\fR, thus remove the latest commit\.
.
.SH "EXAMPLES"
Removes the latest commit\.
.
.IP "" 4
.
.nf

$ git back
.
.fi
.
.IP "" 0
.
.P
Remove the latest 3 commits:
.
.IP "" 4
.
.nf

$ git back 3
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Kenneth Reitz <\fIme@kennethreitz\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
