.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "GIT\-PULL\-REQUEST" "1" "August 2020" "" "Git Extras"
.SH "NAME"
\fBgit\-pull\-request\fR \- Create pull request for GitHub project
.SH "SYNOPSIS"
\fBgit\-pull\-request\fR [<target branch>]
.SH "DESCRIPTION"
Create pull request for a project on GitHub via command line\.
.P
Uses the email from \fBgit config user\.email\fR to open the pull request\.
.P
Personal access token is required for making API call to open the pull request\.
.P
Makre sure the personal access token has the right \fBOAuth\fR scopes for the repo(s)
.P
use \fBgit config \-\-global \-\-add git\-extras\.personal\-access\-token <your\-personal\-access\-token>\fR
.P
if using mutiple accounts, override the global value in the specific repo using \fBgit config git\-extras\.personal\-access\-token <other\-acc\-personal\-access\-token>\fR
.SH "OPTIONS"
<target branch>
.P
The target branch you want to send pull request to\.
.SH "EXAMPLES"
.nf
$ git pull\-request master
Everything up\-to\-date

  create pull\-request for spacewander/spacewander\-toolbox \'master\'

  title: test
  body:
  base [master]:
  GitHub two\-factor authentication code (leave blank if not set up):

\|\.\|\.\|\.
.fi
.SH "AUTHOR"
Written by Tj Holowaychuk <\fI\%mailto:tj@vision\-media\.ca\fR>
.SH "REPORTING BUGS"
<\fI\%https://github\.com/tj/git\-extras/issues\fR>
.SH "SEE ALSO"
<\fI\%https://github\.com/tj/git\-extras\fR>
