.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UNDO" "1" "March 2011" "" "Git Extras"
.
.SH "NAME"
\fBgit\-undo\fR \- Remove latest commits
.
.SH "SYNOPSIS"
\fBgit\-undo\fR [<commitcount>]
.
.SH "DESCRIPTION"
Removes the latest commits\.
.
.SH "OPTIONS"
<commitcount>
.
.P
Number of commits to remove\. Defaults to \fI1\fR, thus remove the latest commit\.
.
.SH "EXAMPLES"
Removes the latest commit\.
.
.IP "" 4
.
.nf

$ git undo
.
.fi
.
.IP "" 0
.
.P
Remove the latest 3 commits:
.
.IP "" 4
.
.nf

$ git undo 3
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Kenneth Reitz <\fIme@kennethreitz\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
