.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-CREATE\-BRANCH" "1" "July 2017" "" ""
.
.SH "NAME"
\fBgit\-create\-branch\fR \- Create branches
.
.SH "SYNOPSIS"
\fBgit\-create\-branch\fR [\-r|\-\-remote [remote_name]] <branchname>
.
.SH "DESCRIPTION"
Creates local branch named <branchname> and optionally sets up a remote tracking branch\.
.
.SH "OPTIONS"
<\-r|\-\-remote [remote_name]>
.
.P
Setup a remote tracking branch using \fBremote_name\fR\. If \fBremote_name\fR is not supplied, use \fBorigin\fR by default\.
.
.P
<branchname>
.
.P
The name of the branch to create\.
.
.SH "EXAMPLES"
.
.nf

$ git create\-branch integration

$ git create\-branch \-r integration

$ git create\-branch \-r upstream integration
.
.fi
.
.SH "AUTHOR"
Written by Jonhnny Weslley <\fIjw@jonhnnyweslley\.net\fR>
.
.br
Modified by Mark Pitman <\fImark\.pitman@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
