.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SHOW\-UNMERGED\-BRANCHES" "1" "October 2017" "" "Git Extras"
.
.SH "NAME"
\fBgit\-show\-unmerged\-branches\fR \- Show unmerged branches
.
.SH "SYNOPSIS"
\fBgit\-show\-unmerged\-branches\fR
.
.SH "DESCRIPTION"
Show all branches not merged in to current HEAD\.
.
.SH "EXAMPLES"
.
.nf

$ git show\-unmerged\-branches
.
.fi
.
.SH "AUTHOR"
Written by Paul Schreiber <\fIpaulschreiber@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
