.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-IGNORE\-IO" "1" "January 2023" "" "Git Extras"
.
.SH "NAME"
\fBgit\-ignore\-io\fR \- Get sample gitignore file
.
.SH "SYNOPSIS"
\fBgit ignore\-io\fR [<OPTIONS>]
.
.SH "DESCRIPTION"
Get sample gitignore file from gitignore\.io \fIhttps://www\.toptal\.com/developers/gitignore/\fR
.
.SH "OPTIONS"
<OPTIONS>
.
.P
\-a, \-\-append <types>\.\.\.
.
.br
Append new \.gitignore content to \.gitignore under the current directory
.
.P
\-r, \-\-replace <types>\.\.\.
.
.br
Export new \.gitignore to the current directory (The old one will be replaced)
.
.P
\-l, \-\-list\-in\-table
.
.br
Print available types in table format
.
.P
\-L, \-\-list\-alphabetically
.
.br
Print available types in alphabetical order
.
.P
\-s, \-\-search <word>
.
.br
Search word in available types
.
.P
\-t, \-\-show\-update\-time
.
.br
Show the last modified time of ~/\.gi_list (where the list of available types is stored)
.
.P
\-u, \-\-update\-list
.
.br
Update ~/\.gi_list
.
.SH "EXAMPLES"
Show sample gitignore file for vim
.
.IP "" 4
.
.nf

$ git ignore\-io vim

    # Created by https://www\.toptal\.com/developers/gitignore/api/vim

    ### Vim ###
    [\._]*\.s[a\-w][a\-z]
    [\._]s[a\-w][a\-z]
    *\.un~
    Session\.vim
    \.netrwhist
    *~
.
.fi
.
.IP "" 0
.
.P
Append sample gitignore for Vim and Python to \.gitignore in current directory\.
.
.IP "" 4
.
.nf

$ git ignore\-io \-a vim python
.
.fi
.
.IP "" 0
.
.P
Show all available types
.
.IP "" 4
.
.nf

$ git ignore\-io \-l

    actionscript             ada                      agda                     android                  anjuta
    appceleratortitanium     appcode                  appengine                archives                 archlinuxpackages
    autotools                basercms                 bazel                    bluej                    bower
    bricxcc                  c                        c++                      cakephp                  carthage
    \.\.\.\.\.\.
.
.fi
.
.IP "" 0
.
.P
Search ja in all available types
.
.IP "" 4
.
.nf

$ git ignore\-io \-s ja

    django
    jabref
    java
    ninja
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Lee\-W \fIweilee\.rx@gmail\.com\fR
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
