.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PR" "1" "September 2020" "" "Git Extras"
.
.SH "NAME"
\fBgit\-pr\fR \- Checks out a pull request locally
.
.SH "SYNOPSIS"
\fBgit\-pr\fR [\-m|\-\-merge] <number> [<remote>]
.
.br
\fBgit\-pr\fR [\-m|\-\-merge] <[remote]:number>\.\.\.
.
.br
\fBgit\-pr\fR [\-m|\-\-merge] <url>\.\.\.
.
.br
\fBgit\-pr clean\fR
.
.SH "DESCRIPTION"
Creates a local branch based on a GitHub pull request number or URL, and switch to that branch afterwards\.
.
.SH "OPTIONS"
<remote>
.
.P
The name of the remote to fetch from\. Defaults to \fBorigin\fR\.
.
.P
<url>
.
.P
GitHub pull request URL in the format \fBhttps://github\.com/tj/git\-extras/pull/453\fR\.
.
.P
\-m | \-\-merge
.
.P
Checkout a merge commit against the branch the pull request is targeting\. Because this feature uses a private API with which GitHub checks the pull request\'s mergeability, it only works with the opened pull request\. If the merge commit is not up\-to\-date, please visit the pull request web page to trigger the rebuild\.
.
.SH "EXAMPLES"
This checks out the pull request \fB226\fR from \fBorigin\fR:
.
.IP "" 4
.
.nf

$ git pr 226

remote: Counting objects: 12, done\.
remote: Compressing objects: 100% (9/9), done\.
remote: Total 12 (delta 3), reused 9 (delta 3)
Unpacking objects: 100% (12/12), done\.
From https://github\.com/tj/git\-extras
 * [new ref]         refs/pull/226/head \-> pr/226

Switched to branch \'pr/226\'
.
.fi
.
.IP "" 0
.
.P
This pulls from a different remote:
.
.IP "" 4
.
.nf

$ git pr 226 upstream
.
.fi
.
.IP "" 0
.
.P
This does the same thing as the command above:
.
.IP "" 4
.
.nf

$ git pr upstream:226
.
.fi
.
.IP "" 0
.
.P
You can also checkout a pull request based on a GitHub URL:
.
.IP "" 4
.
.nf

$ git pr https://github\.com/tj/git\-extras/pull/453

From https://github\.com/tj/git\-extras
 * [new ref]         refs/pull/453/head \-> pr/453
Switched to branch \'pr/453\'
.
.fi
.
.IP "" 0
.
.P
You could even pull multiple pull requests via the GitHub URL or the ID \fBwith remote specified\fR:
.
.IP "" 4
.
.nf

$ git pr upstream:226 upstream:443
$ git pr upstream:443 https://github\.com/tj/git\-extras/pull/453
.
.fi
.
.IP "" 0
.
.P
Note that \fBgit pr PR\-A PR\-B\fR is equal to:
.
.IP "" 4
.
.nf

$ git pr PR\-A
$ git pr PR\-B
.
.fi
.
.IP "" 0
.
.P
Therefore, if one of the pull request is failed to pull, this command will still go ahead and pull the others\. The final exit code will be decided by the result of the final pulling\.
.
.P
With \fB\-\-merge\fR option, you could check out a merge commit:
.
.IP "" 4
.
.nf

$ git pr origin:755 \-\-merge
remote: Enumerating objects: 3, done\.
remote: Counting objects: 100% (3/3), done\.
remote: Compressing objects: 100% (3/3), done\.
remote: Total 3 (delta 0), reused 0 (delta 0), pack\-reused 0
Unpacking objects: 100% (3/3), done\.
From github\.com:tj/git\-extras
bf7dd69\.\.de6e51c  refs/pull/755/merge \-> pr/755
Switched to branch \'pr/775\'

$ git log pr/775 \-\-oneline
de6e51c (pr/755) Merge bf7dd6\.\.\.
.
.fi
.
.IP "" 0
.
.P
To clean up old branches:
.
.IP "" 4
.
.nf

$ git pr clean

Deleted branch pr/226 (was b96a8c2)\.
Deleted branch pr/220 (was d34dc0f)\.
Deleted branch pr/775 (was de6e51c)\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Originally from https://gist\.github\.com/gnarf/5406589
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/tj/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/tj/git\-extras\fR>
