.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-RELEASE" "1" "October 2010" "" "Git Extras"
.
.SH "NAME"
\fBgit\-release\fR \- Commit, tag and push changes to the repository
.
.SH "SYNOPSIS"
\fBgit\-release\fR <tagname>
.
.SH "DESCRIPTION"
Commits changes with message "Release <tagname>", tags with the given <tagname> and pushes the branch / tags\.
.
.SH "OPTIONS"
<tagname>
.
.SH "EXAMPLES"
Release commit with the given <tagname>\.
.
.IP "" 4
.
.nf

$ git release 0\.1\.0
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
