.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UPDATE\-EXTRAS" "1" "October 2010" "" "Git Extras"
.
.SH "NAME"
\fBgit\-update\-extras\fR \- Updates git extras
.
.SH "SYNOPSIS"
\fBgit\-update\-extras\fR
.
.SH "DESCRIPTION"
Updates git extras\. Clones the repo to \fI/tmp/git\-extras\fR, make installs, then cds back to the origin directory\.
.
.SH "AUTHOR"
Written by Tj Holowaychuk <\fItj@vision\-media\.ca\fR>
.
.SH "REPORTING BUGS"
<\fIhttp://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttp://github\.com/visionmedia/git\-extras\fR>
