.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UNLOCK" "1" "December 2013" "" ""
.
.SH "NAME"
\fBgit\-unlock\fR \- Unlock a file excluded from version control
.
.SH "SYNOPSIS"
\fBgit\-lock\fR <filename>
.
.SH "DESCRIPTION"
Unlock local files from version control\.
.
.SH "OPTIONS"
<filename>
.
.P
The name of the filename\.
.
.SH "EXAMPLES"
.
.nf

$ git unlock config/database\.yml
.
.fi
.
.SH "AUTHOR"
Written by Julio Napuri <\fIjulionc@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/visionmedia/git\-extras\fR>
