.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-ARCHIVE\-FILE" "1" "February 2013" "" "Git Extras"
.
.SH "NAME"
\fBgit\-archive\-file\fR \- Export the current HEAD of the git repository to a archive
.
.SH "SYNOPSIS"
\fBgit\-archive\-file\fR
.
.SH "DESCRIPTION"
Export the current HEAD of the repository into a archive with a identifiable and unique name\.
.
.SH "OPTIONS"
This command does not take any options\.
.
.SH "EXAMPLES"
Archive naming conventions:
.
.P
On any branch: \fBgit\-extras\.1\.7\.0\-110\-gafefba7\.branch\-name\.zip\fR
.
.P
On master branch: \fBgit\-extras\.1\.7\.0\-110\-gafefba7\.zip\fR
.
.P
On a detached HEAD (e\.g\. a tag): \fBgit\-extras\.1\.7\.0\.zip\fR
.
.SH "AUTHOR"
Written by Philipp Klose <\fIme@thehippo\.de\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/visionmedia/git\-extras\fR>
