name: "Maintenance: Close Stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  pull-requests: "write"

jobs:
  stale:
    runs-on: "ubuntu-latest"
    if: github.repository_owner == 'tj'
    steps:
      - uses: "actions/stale@v9"
        with:
          close-pr-message: "This PR was closed because it has been stalled for 365 days with no activity. Feel free to make a new PR if you wish to continue"
          days-before-pr-stale: 350
          days-before-pr-close: 15
